"""
配置模块
"""
from .api_config import API_KEY, API_URL, API_MODEL, API_TIMEOUT
from .model_config import (
    TEMPERATURE, MAX_TOKENS,
    BATCH_SIZE, MAX_CONCURRENCY, BATCH_DELAY, REQUEST_DELAY,
    DATASET_CONFIGS
)
from .mind_config import (
    SSR_K, SSR_EMBEDDING_MODEL, SSR_TFIDF_MAX_FEATURES,
    RID_NUM_EXAMPLES, RID_MAX_RULES,
    IAI_MAX_THOUGHT_LENGTH
)
from .indicators_config import FAKE_INDICATORS, REAL_INDICATORS
from .prompt_config import (
    RID_PROMPT_TEMPLATE,
    IAI_DEBATER_PROMPT_TEMPLATE,
    IAI_JUDGE_PROMPT_TEMPLATE,
    SIMPLE_PROMPT_TEMPLATE
)

__all__ = [
    # API 配置
    "API_KEY", "API_URL", "API_MODEL", "API_TIMEOUT",
    # 模型配置
    "TEMPERATURE", "MAX_TOKENS",
    "BATCH_SIZE", "MAX_CONCURRENCY", "BATCH_DELAY", "REQUEST_DELAY",
    "DATASET_CONFIGS",
    # MIND 配置
    "SSR_K", "SSR_EMBEDDING_MODEL", "SSR_TFIDF_MAX_FEATURES",
    "RID_NUM_EXAMPLES", "RID_MAX_RULES",
    "IAI_MAX_THOUGHT_LENGTH",
    # 指标配置
    "FAKE_INDICATORS", "REAL_INDICATORS",
    # Prompt 配置
    "RID_PROMPT_TEMPLATE",
    "IAI_DEBATER_PROMPT_TEMPLATE",
    "IAI_JUDGE_PROMPT_TEMPLATE",
    "SIMPLE_PROMPT_TEMPLATE"
]

